### ISSUE TITLE
我clone下来，发现运行不了。

### ISSUE THREAD

**Issue by qknow-w** [J-F-Liu/webpack-react-boilerplate#1]
你好，问题如下
![qwe.png](http://upload-images.jianshu.io/upload_images/1430231-3f43e25f0b5c8853.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240))
我也正好在学习react，发现在你这个项目非常好。

**Comment by J-F-Liu** [comment]
Windows系统安装和编译node sass需要安装Python 2.7和[Visual C++ Build Tools](https://blogs.msdn.microsoft.com/vcblog/2016/03/31/announcing-the-official-release-of-the-visual-c-build-tools-2015/)
然后
npm install node-sass --msvs_version=2015
npm rebuild node-sass

**Comment by qknow-w** [comment]
好的，谢谢。你有没有想法搞个开源的项目呢，我觉得你这个再配合[material-ui](https://github.com/callemall/material-ui),感觉非常爽。

**Comment by J-F-Liu** [comment]
@503945930 新开始了个项目[https://github.com/J-F-Liu/syntax-compare](https://github.com/J-F-Liu/syntax-compare)，有兴趣参与吗

**Comment by qknow-w** [comment]
可以的，希望可以一起参与。

**Comment by qknow-w** [comment]
看了下这个项目，还有比较有趣，我怎么参与呢。

**Comment by J-F-Liu** [comment]
编辑languages目录下面的文件，添加各种语法元素的样例代码
